// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bar/v1/bar.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bar represents the bar domain entity.
type Bar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Bar           string                 `protobuf:"bytes,3,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_bar_v1_bar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_bar_v1_bar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_bar_v1_bar_proto_rawDescGZIP(), []int{0}
}

func (x *Bar) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bar) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Bar) GetBar() string {
	if x != nil {
		return x.Bar
	}
	return ""
}

// CreateBarRequest is the request message for CreateBar.
type CreateBarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Bar           string                 `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBarRequest) Reset() {
	*x = CreateBarRequest{}
	mi := &file_bar_v1_bar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBarRequest) ProtoMessage() {}

func (x *CreateBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bar_v1_bar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBarRequest.ProtoReflect.Descriptor instead.
func (*CreateBarRequest) Descriptor() ([]byte, []int) {
	return file_bar_v1_bar_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBarRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateBarRequest) GetBar() string {
	if x != nil {
		return x.Bar
	}
	return ""
}

// GetBarRequest is the request message for GetBar.
type GetBarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarRequest) Reset() {
	*x = GetBarRequest{}
	mi := &file_bar_v1_bar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarRequest) ProtoMessage() {}

func (x *GetBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bar_v1_bar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarRequest.ProtoReflect.Descriptor instead.
func (*GetBarRequest) Descriptor() ([]byte, []int) {
	return file_bar_v1_bar_proto_rawDescGZIP(), []int{2}
}

func (x *GetBarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListBarsRequest is the request message for ListBars.
type ListBarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBarsRequest) Reset() {
	*x = ListBarsRequest{}
	mi := &file_bar_v1_bar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBarsRequest) ProtoMessage() {}

func (x *ListBarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bar_v1_bar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBarsRequest.ProtoReflect.Descriptor instead.
func (*ListBarsRequest) Descriptor() ([]byte, []int) {
	return file_bar_v1_bar_proto_rawDescGZIP(), []int{3}
}

func (x *ListBarsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBarsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBarsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// ListBarsResponse is the response message for ListBars.
type ListBarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bars          []*Bar                 `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBarsResponse) Reset() {
	*x = ListBarsResponse{}
	mi := &file_bar_v1_bar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBarsResponse) ProtoMessage() {}

func (x *ListBarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bar_v1_bar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBarsResponse.ProtoReflect.Descriptor instead.
func (*ListBarsResponse) Descriptor() ([]byte, []int) {
	return file_bar_v1_bar_proto_rawDescGZIP(), []int{4}
}

func (x *ListBarsResponse) GetBars() []*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

func (x *ListBarsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListBarsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBarsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// UpdateBarRequest is the request message for UpdateBar.
type UpdateBarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Bar           string                 `protobuf:"bytes,3,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBarRequest) Reset() {
	*x = UpdateBarRequest{}
	mi := &file_bar_v1_bar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBarRequest) ProtoMessage() {}

func (x *UpdateBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bar_v1_bar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBarRequest.ProtoReflect.Descriptor instead.
func (*UpdateBarRequest) Descriptor() ([]byte, []int) {
	return file_bar_v1_bar_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBarRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateBarRequest) GetBar() string {
	if x != nil {
		return x.Bar
	}
	return ""
}

// DeleteBarRequest is the request message for DeleteBar.
type DeleteBarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBarRequest) Reset() {
	*x = DeleteBarRequest{}
	mi := &file_bar_v1_bar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBarRequest) ProtoMessage() {}

func (x *DeleteBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bar_v1_bar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBarRequest.ProtoReflect.Descriptor instead.
func (*DeleteBarRequest) Descriptor() ([]byte, []int) {
	return file_bar_v1_bar_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_bar_v1_bar_proto protoreflect.FileDescriptor

const file_bar_v1_bar_proto_rawDesc = "" +
	"\n" +
	"\x10bar/v1/bar.proto\x12\x06bar.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"J\n" +
	"\x03Bar\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x03R\x02id\x12\x17\n" +
	"\x04code\x18\x02 \x01(\tB\x03\xe0A\x03R\x04code\x12\x15\n" +
	"\x03bar\x18\x03 \x01(\tB\x03\xe0A\x03R\x03bar\"B\n" +
	"\x10CreateBarRequest\x12\x17\n" +
	"\x04code\x18\x01 \x01(\tB\x03\xe0A\x02R\x04code\x12\x15\n" +
	"\x03bar\x18\x02 \x01(\tB\x03\xe0A\x02R\x03bar\"$\n" +
	"\rGetBarRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"d\n" +
	"\x0fListBarsRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05B\x03\xe0A\x01R\x04page\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05B\x03\xe0A\x01R\x05limit\x12\x1d\n" +
	"\akeyword\x18\x03 \x01(\tB\x03\xe0A\x01R\akeyword\"s\n" +
	"\x10ListBarsResponse\x12\x1f\n" +
	"\x04bars\x18\x01 \x03(\v2\v.bar.v1.BarR\x04bars\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"W\n" +
	"\x10UpdateBarRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12\x17\n" +
	"\x04code\x18\x02 \x01(\tB\x03\xe0A\x02R\x04code\x12\x15\n" +
	"\x03bar\x18\x03 \x01(\tB\x03\xe0A\x02R\x03bar\"'\n" +
	"\x10DeleteBarRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id2\xa0\x02\n" +
	"\n" +
	"BarService\x122\n" +
	"\tCreateBar\x12\x18.bar.v1.CreateBarRequest\x1a\v.bar.v1.Bar\x12,\n" +
	"\x06GetBar\x12\x15.bar.v1.GetBarRequest\x1a\v.bar.v1.Bar\x12=\n" +
	"\bListBars\x12\x17.bar.v1.ListBarsRequest\x1a\x18.bar.v1.ListBarsResponse\x122\n" +
	"\tUpdateBar\x12\x18.bar.v1.UpdateBarRequest\x1a\v.bar.v1.Bar\x12=\n" +
	"\tDeleteBar\x12\x18.bar.v1.DeleteBarRequest\x1a\x16.google.protobuf.EmptyB0Z.github.com/arisatriop/goilerplate-proto/bar/v1b\x06proto3"

var (
	file_bar_v1_bar_proto_rawDescOnce sync.Once
	file_bar_v1_bar_proto_rawDescData []byte
)

func file_bar_v1_bar_proto_rawDescGZIP() []byte {
	file_bar_v1_bar_proto_rawDescOnce.Do(func() {
		file_bar_v1_bar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bar_v1_bar_proto_rawDesc), len(file_bar_v1_bar_proto_rawDesc)))
	})
	return file_bar_v1_bar_proto_rawDescData
}

var file_bar_v1_bar_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bar_v1_bar_proto_goTypes = []any{
	(*Bar)(nil),              // 0: bar.v1.Bar
	(*CreateBarRequest)(nil), // 1: bar.v1.CreateBarRequest
	(*GetBarRequest)(nil),    // 2: bar.v1.GetBarRequest
	(*ListBarsRequest)(nil),  // 3: bar.v1.ListBarsRequest
	(*ListBarsResponse)(nil), // 4: bar.v1.ListBarsResponse
	(*UpdateBarRequest)(nil), // 5: bar.v1.UpdateBarRequest
	(*DeleteBarRequest)(nil), // 6: bar.v1.DeleteBarRequest
	(*emptypb.Empty)(nil),    // 7: google.protobuf.Empty
}
var file_bar_v1_bar_proto_depIdxs = []int32{
	0, // 0: bar.v1.ListBarsResponse.bars:type_name -> bar.v1.Bar
	1, // 1: bar.v1.BarService.CreateBar:input_type -> bar.v1.CreateBarRequest
	2, // 2: bar.v1.BarService.GetBar:input_type -> bar.v1.GetBarRequest
	3, // 3: bar.v1.BarService.ListBars:input_type -> bar.v1.ListBarsRequest
	5, // 4: bar.v1.BarService.UpdateBar:input_type -> bar.v1.UpdateBarRequest
	6, // 5: bar.v1.BarService.DeleteBar:input_type -> bar.v1.DeleteBarRequest
	0, // 6: bar.v1.BarService.CreateBar:output_type -> bar.v1.Bar
	0, // 7: bar.v1.BarService.GetBar:output_type -> bar.v1.Bar
	4, // 8: bar.v1.BarService.ListBars:output_type -> bar.v1.ListBarsResponse
	0, // 9: bar.v1.BarService.UpdateBar:output_type -> bar.v1.Bar
	7, // 10: bar.v1.BarService.DeleteBar:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bar_v1_bar_proto_init() }
func file_bar_v1_bar_proto_init() {
	if File_bar_v1_bar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bar_v1_bar_proto_rawDesc), len(file_bar_v1_bar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bar_v1_bar_proto_goTypes,
		DependencyIndexes: file_bar_v1_bar_proto_depIdxs,
		MessageInfos:      file_bar_v1_bar_proto_msgTypes,
	}.Build()
	File_bar_v1_bar_proto = out.File
	file_bar_v1_bar_proto_goTypes = nil
	file_bar_v1_bar_proto_depIdxs = nil
}
