// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: foo/v1/foo.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Foo represents the foo domain entity.
type Foo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Foo) Reset() {
	*x = Foo{}
	mi := &file_foo_v1_foo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_foo_v1_foo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_foo_v1_foo_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Foo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Foo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CreateFooRequest is the request message for CreateFoo.
type CreateFooRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFooRequest) Reset() {
	*x = CreateFooRequest{}
	mi := &file_foo_v1_foo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFooRequest) ProtoMessage() {}

func (x *CreateFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foo_v1_foo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFooRequest.ProtoReflect.Descriptor instead.
func (*CreateFooRequest) Descriptor() ([]byte, []int) {
	return file_foo_v1_foo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFooRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateFooRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CreateFooResponse is the response message for CreateFoo.
type CreateFooResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foo           *Foo                   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFooResponse) Reset() {
	*x = CreateFooResponse{}
	mi := &file_foo_v1_foo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFooResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFooResponse) ProtoMessage() {}

func (x *CreateFooResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foo_v1_foo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFooResponse.ProtoReflect.Descriptor instead.
func (*CreateFooResponse) Descriptor() ([]byte, []int) {
	return file_foo_v1_foo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFooResponse) GetFoo() *Foo {
	if x != nil {
		return x.Foo
	}
	return nil
}

// GetFooRequest is the request message for GetFoo.
type GetFooRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFooRequest) Reset() {
	*x = GetFooRequest{}
	mi := &file_foo_v1_foo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFooRequest) ProtoMessage() {}

func (x *GetFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foo_v1_foo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFooRequest.ProtoReflect.Descriptor instead.
func (*GetFooRequest) Descriptor() ([]byte, []int) {
	return file_foo_v1_foo_proto_rawDescGZIP(), []int{3}
}

func (x *GetFooRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetFooResponse is the response message for GetFoo.
type GetFooResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foo           *Foo                   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFooResponse) Reset() {
	*x = GetFooResponse{}
	mi := &file_foo_v1_foo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFooResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFooResponse) ProtoMessage() {}

func (x *GetFooResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foo_v1_foo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFooResponse.ProtoReflect.Descriptor instead.
func (*GetFooResponse) Descriptor() ([]byte, []int) {
	return file_foo_v1_foo_proto_rawDescGZIP(), []int{4}
}

func (x *GetFooResponse) GetFoo() *Foo {
	if x != nil {
		return x.Foo
	}
	return nil
}

// ListFoosRequest is the request message for ListFoos.
type ListFoosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoosRequest) Reset() {
	*x = ListFoosRequest{}
	mi := &file_foo_v1_foo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoosRequest) ProtoMessage() {}

func (x *ListFoosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foo_v1_foo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoosRequest.ProtoReflect.Descriptor instead.
func (*ListFoosRequest) Descriptor() ([]byte, []int) {
	return file_foo_v1_foo_proto_rawDescGZIP(), []int{5}
}

func (x *ListFoosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFoosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFoosRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// ListFoosResponse is the response message for ListFoos.
type ListFoosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foos          []*Foo                 `protobuf:"bytes,1,rep,name=foos,proto3" json:"foos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoosResponse) Reset() {
	*x = ListFoosResponse{}
	mi := &file_foo_v1_foo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoosResponse) ProtoMessage() {}

func (x *ListFoosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foo_v1_foo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoosResponse.ProtoReflect.Descriptor instead.
func (*ListFoosResponse) Descriptor() ([]byte, []int) {
	return file_foo_v1_foo_proto_rawDescGZIP(), []int{6}
}

func (x *ListFoosResponse) GetFoos() []*Foo {
	if x != nil {
		return x.Foos
	}
	return nil
}

func (x *ListFoosResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFoosResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFoosResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// UpdateFooRequest is the request message for UpdateFoo.
type UpdateFooRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFooRequest) Reset() {
	*x = UpdateFooRequest{}
	mi := &file_foo_v1_foo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFooRequest) ProtoMessage() {}

func (x *UpdateFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foo_v1_foo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFooRequest.ProtoReflect.Descriptor instead.
func (*UpdateFooRequest) Descriptor() ([]byte, []int) {
	return file_foo_v1_foo_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateFooRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFooRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateFooRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// UpdateFooResponse is the response message for UpdateFoo.
type UpdateFooResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foo           *Foo                   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFooResponse) Reset() {
	*x = UpdateFooResponse{}
	mi := &file_foo_v1_foo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFooResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFooResponse) ProtoMessage() {}

func (x *UpdateFooResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foo_v1_foo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFooResponse.ProtoReflect.Descriptor instead.
func (*UpdateFooResponse) Descriptor() ([]byte, []int) {
	return file_foo_v1_foo_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFooResponse) GetFoo() *Foo {
	if x != nil {
		return x.Foo
	}
	return nil
}

// DeleteFooRequest is the request message for DeleteFoo.
type DeleteFooRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFooRequest) Reset() {
	*x = DeleteFooRequest{}
	mi := &file_foo_v1_foo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFooRequest) ProtoMessage() {}

func (x *DeleteFooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foo_v1_foo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFooRequest.ProtoReflect.Descriptor instead.
func (*DeleteFooRequest) Descriptor() ([]byte, []int) {
	return file_foo_v1_foo_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFooRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteFooResponse is the response message for DeleteFoo.
type DeleteFooResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFooResponse) Reset() {
	*x = DeleteFooResponse{}
	mi := &file_foo_v1_foo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFooResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFooResponse) ProtoMessage() {}

func (x *DeleteFooResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foo_v1_foo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFooResponse.ProtoReflect.Descriptor instead.
func (*DeleteFooResponse) Descriptor() ([]byte, []int) {
	return file_foo_v1_foo_proto_rawDescGZIP(), []int{10}
}

var File_foo_v1_foo_proto protoreflect.FileDescriptor

const file_foo_v1_foo_proto_rawDesc = "" +
	"\n" +
	"\x10foo/v1/foo.proto\x12\x06foo.v1\"=\n" +
	"\x03Foo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\":\n" +
	"\x10CreateFooRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"2\n" +
	"\x11CreateFooResponse\x12\x1d\n" +
	"\x03foo\x18\x01 \x01(\v2\v.foo.v1.FooR\x03foo\"\x1f\n" +
	"\rGetFooRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x0eGetFooResponse\x12\x1d\n" +
	"\x03foo\x18\x01 \x01(\v2\v.foo.v1.FooR\x03foo\"U\n" +
	"\x0fListFoosRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"s\n" +
	"\x10ListFoosResponse\x12\x1f\n" +
	"\x04foos\x18\x01 \x03(\v2\v.foo.v1.FooR\x04foos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"J\n" +
	"\x10UpdateFooRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"2\n" +
	"\x11UpdateFooResponse\x12\x1d\n" +
	"\x03foo\x18\x01 \x01(\v2\v.foo.v1.FooR\x03foo\"\"\n" +
	"\x10DeleteFooRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11DeleteFooResponse2\xca\x02\n" +
	"\n" +
	"FooService\x12@\n" +
	"\tCreateFoo\x12\x18.foo.v1.CreateFooRequest\x1a\x19.foo.v1.CreateFooResponse\x127\n" +
	"\x06GetFoo\x12\x15.foo.v1.GetFooRequest\x1a\x16.foo.v1.GetFooResponse\x12=\n" +
	"\bListFoos\x12\x17.foo.v1.ListFoosRequest\x1a\x18.foo.v1.ListFoosResponse\x12@\n" +
	"\tUpdateFoo\x12\x18.foo.v1.UpdateFooRequest\x1a\x19.foo.v1.UpdateFooResponse\x12@\n" +
	"\tDeleteFoo\x12\x18.foo.v1.DeleteFooRequest\x1a\x19.foo.v1.DeleteFooResponseB0Z.github.com/arisatriop/goilerplate-proto/foo/v1b\x06proto3"

var (
	file_foo_v1_foo_proto_rawDescOnce sync.Once
	file_foo_v1_foo_proto_rawDescData []byte
)

func file_foo_v1_foo_proto_rawDescGZIP() []byte {
	file_foo_v1_foo_proto_rawDescOnce.Do(func() {
		file_foo_v1_foo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_foo_v1_foo_proto_rawDesc), len(file_foo_v1_foo_proto_rawDesc)))
	})
	return file_foo_v1_foo_proto_rawDescData
}

var file_foo_v1_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_foo_v1_foo_proto_goTypes = []any{
	(*Foo)(nil),               // 0: foo.v1.Foo
	(*CreateFooRequest)(nil),  // 1: foo.v1.CreateFooRequest
	(*CreateFooResponse)(nil), // 2: foo.v1.CreateFooResponse
	(*GetFooRequest)(nil),     // 3: foo.v1.GetFooRequest
	(*GetFooResponse)(nil),    // 4: foo.v1.GetFooResponse
	(*ListFoosRequest)(nil),   // 5: foo.v1.ListFoosRequest
	(*ListFoosResponse)(nil),  // 6: foo.v1.ListFoosResponse
	(*UpdateFooRequest)(nil),  // 7: foo.v1.UpdateFooRequest
	(*UpdateFooResponse)(nil), // 8: foo.v1.UpdateFooResponse
	(*DeleteFooRequest)(nil),  // 9: foo.v1.DeleteFooRequest
	(*DeleteFooResponse)(nil), // 10: foo.v1.DeleteFooResponse
}
var file_foo_v1_foo_proto_depIdxs = []int32{
	0,  // 0: foo.v1.CreateFooResponse.foo:type_name -> foo.v1.Foo
	0,  // 1: foo.v1.GetFooResponse.foo:type_name -> foo.v1.Foo
	0,  // 2: foo.v1.ListFoosResponse.foos:type_name -> foo.v1.Foo
	0,  // 3: foo.v1.UpdateFooResponse.foo:type_name -> foo.v1.Foo
	1,  // 4: foo.v1.FooService.CreateFoo:input_type -> foo.v1.CreateFooRequest
	3,  // 5: foo.v1.FooService.GetFoo:input_type -> foo.v1.GetFooRequest
	5,  // 6: foo.v1.FooService.ListFoos:input_type -> foo.v1.ListFoosRequest
	7,  // 7: foo.v1.FooService.UpdateFoo:input_type -> foo.v1.UpdateFooRequest
	9,  // 8: foo.v1.FooService.DeleteFoo:input_type -> foo.v1.DeleteFooRequest
	2,  // 9: foo.v1.FooService.CreateFoo:output_type -> foo.v1.CreateFooResponse
	4,  // 10: foo.v1.FooService.GetFoo:output_type -> foo.v1.GetFooResponse
	6,  // 11: foo.v1.FooService.ListFoos:output_type -> foo.v1.ListFoosResponse
	8,  // 12: foo.v1.FooService.UpdateFoo:output_type -> foo.v1.UpdateFooResponse
	10, // 13: foo.v1.FooService.DeleteFoo:output_type -> foo.v1.DeleteFooResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_foo_v1_foo_proto_init() }
func file_foo_v1_foo_proto_init() {
	if File_foo_v1_foo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foo_v1_foo_proto_rawDesc), len(file_foo_v1_foo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foo_v1_foo_proto_goTypes,
		DependencyIndexes: file_foo_v1_foo_proto_depIdxs,
		MessageInfos:      file_foo_v1_foo_proto_msgTypes,
	}.Build()
	File_foo_v1_foo_proto = out.File
	file_foo_v1_foo_proto_goTypes = nil
	file_foo_v1_foo_proto_depIdxs = nil
}
